package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF) // Soft Lavender primary
val PurpleGrey80 = Color(0xFFCCC2DC) // Muted Lavender secondary
val Pink80 = Color(0xFFEFB8C8) // Rose-lavender tertiary

val Purple40 = Color(0xFF6750A4) // Royal deep purple primary
val PurpleGrey40 = Color(0xFF625B71) // Muted deep slate purple
val Pink40 = Color(0xFF7D5260) // Deep rose accent

// Green M3 Fallback Scheme (Light)
val GreenPrimaryLight = Color(0xFF006D3E)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFF9FF7B9)
val GreenOnPrimaryContainerLight = Color(0xFF00210E)
val GreenSecondaryLight = Color(0xFF4F6354)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFD2E8D5)
val GreenOnSecondaryContainerLight = Color(0xFF0C1F13)
val GreenTertiaryLight = Color(0xFF3B6573)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFBEEBFD)
val GreenOnTertiaryContainerLight = Color(0xFF001F29)
val GreenBackgroundLight = Color(0xFFFBFDF8)
val GreenOnBackgroundLight = Color(0xFF191C1A)
val GreenSurfaceLight = Color(0xFFFBFDF8)
val GreenOnSurfaceLight = Color(0xFF191C1A)
val GreenSurfaceVariantLight = Color(0xFFDDE5DB)
val GreenOnSurfaceVariantLight = Color(0xFF414942)
val GreenOutlineLight = Color(0xFF717972)

// Green M3 Fallback Scheme (Dark)
val GreenPrimaryDark = Color(0xFF81D7A0)
val GreenOnPrimaryDark = Color(0xFF00391E)
val GreenPrimaryContainerDark = Color(0xFF00522D)
val GreenOnPrimaryContainerDark = Color(0xFF9FF7B9)
val GreenSecondaryDark = Color(0xFFB6CCBA)
val GreenOnSecondaryDark = Color(0xFF243528)
val GreenSecondaryContainerDark = Color(0xFF3A4B3E)
val GreenOnSecondaryContainerDark = Color(0xFFD2E8D5)
val GreenTertiaryDark = Color(0xFFA2CEDF)
val GreenOnTertiaryDark = Color(0xFF053543)
val GreenTertiaryContainerDark = Color(0xFF224D5B)
val GreenOnTertiaryContainerDark = Color(0xFFBEEBFD)
val GreenBackgroundDark = Color(0xFF0E120F)
val GreenOnBackgroundDark = Color(0xFFE1E3DF)
val GreenSurfaceDark = Color(0xFF111412)
val GreenOnSurfaceDark = Color(0xFFE1E3DF)
val GreenSurfaceVariantDark = Color(0xFF414942)
val GreenOnSurfaceVariantDark = Color(0xFFC1C9BF)
val GreenOutlineDark = Color(0xFF8B938A)

// Monochromatic Fallback Scheme (Light)
val MonoPrimaryLight = Color(0xFF000000)
val MonoOnPrimaryLight = Color(0xFFFFFFFF)
val MonoPrimaryContainerLight = Color(0xFFE5E5E5)
val MonoOnPrimaryContainerLight = Color(0xFF000000)
val MonoSecondaryLight = Color(0xFF333333)
val MonoOnSecondaryLight = Color(0xFFFFFFFF)
val MonoSecondaryContainerLight = Color(0xFFF2F2F2)
val MonoOnSecondaryContainerLight = Color(0xFF000000)
val MonoTertiaryLight = Color(0xFF555555)
val MonoOnTertiaryLight = Color(0xFFFFFFFF)
val MonoTertiaryContainerLight = Color(0xFFEAEAEA)
val MonoOnTertiaryContainerLight = Color(0xFF111111)
val MonoBackgroundLight = Color(0xFFFFFFFF)
val MonoOnBackgroundLight = Color(0xFF000000)
val MonoSurfaceLight = Color(0xFFFAFAFA)
val MonoOnSurfaceLight = Color(0xFF000000)
val MonoSurfaceVariantLight = Color(0xFFEEEEEE)
val MonoOnSurfaceVariantLight = Color(0xFF222222)
val MonoOutlineLight = Color(0xFF777777)

// Monochromatic Fallback Scheme (Dark)
val MonoPrimaryDark = Color(0xFFFFFFFF)
val MonoOnPrimaryDark = Color(0xFF000000)
val MonoPrimaryContainerDark = Color(0xFF222222)
val MonoOnPrimaryContainerDark = Color(0xFFFFFFFF)
val MonoSecondaryDark = Color(0xFFCCCCCC)
val MonoOnSecondaryDark = Color(0xFF000000)
val MonoSecondaryContainerDark = Color(0xFF1E1E1E)
val MonoOnSecondaryContainerDark = Color(0xFFFFFFFF)
val MonoTertiaryDark = Color(0xFFAAAAAA)
val MonoOnTertiaryDark = Color(0xFF000000)
val MonoTertiaryContainerDark = Color(0xFF2A2A2A)
val MonoOnTertiaryContainerDark = Color(0xFFEEEEEE)
val MonoBackgroundDark = Color(0xFF121212)
val MonoOnBackgroundDark = Color(0xFFFFFFFF)
val MonoSurfaceDark = Color(0xFF161616)
val MonoOnSurfaceDark = Color(0xFFFFFFFF)
val MonoSurfaceVariantDark = Color(0xFF242424)
val MonoOnSurfaceVariantDark = Color(0xFFDDDDDD)
val MonoOutlineDark = Color(0xFF888888)

